/**
 * FAQAccordion Component Types
 *
 * Type definitions for the brutalist FAQ accordion component
 * with GSAP animations and gold aesthetic.
 */

/**
 * Individual FAQ item containing question and answer text
 */
export interface FAQItem {
  /**
   * Question text - will be displayed in uppercase with DM Mono font
   * @example "What services does The Elites Solutions offer?"
   */
  question: string;

  /**
   * Answer text - supports multiline content
   * @example "We specialize in full-stack web development, mobile applications..."
   */
  answer: string;
}

/**
 * Props for the FAQAccordion component
 */
export interface FAQAccordionProps {
  /**
   * Section heading displayed above FAQ items
   * @default "Frequently Asked Questions"
   */
  title?: string;

  /**
   * Array of FAQ items to display
   * First item opens automatically on mount
   */
  faqs: FAQItem[];

  /**
   * Additional CSS class names for customization
   * @default ""
   */
  className?: string;
}

/**
 * Internal state type for tracking active accordion item
 */
export type ActiveIndex = number | null;

/**
 * Animation configuration for GSAP transitions
 */
export interface AnimationConfig {
  /**
   * Duration for height animations (in seconds)
   * @default 0.5
   */
  heightDuration?: number;

  /**
   * Duration for arrow rotation (in seconds)
   * @default 0.3
   */
  arrowDuration?: number;

  /**
   * Easing function for height transitions
   * @default "power2.out"
   */
  heightEase?: string;

  /**
   * Easing function for arrow rotation
   * @default "back.out(2)"
   */
  arrowEase?: string;
}

/**
 * CSS module styles type (auto-generated by Next.js)
 */
export interface FAQAccordionStyles {
  faqSection: string;
  container: string;
  title: string;
  faqList: string;
  item: string;
  active: string;
  question: string;
  questionText: string;
  arrow: string;
  answerWrapper: string;
  answer: string;
}
