export const servicesData = [
  {
    id: "1",
    number: "01 / 06",
    title: "Web Development",
    image: "/services/web-development.jpg", // Placeholder - can be replaced
    category: "[ Digital Platforms ]",
    slug: "web-development",
  },
  {
    id: "2",
    number: "02 / 06",
    title: "Mobile Applications",
    image: "/services/mobile-apps.jpg",
    category: "[ Native & Cross-Platform ]",
    slug: "mobile-apps",
  },
  {
    id: "3",
    number: "03 / 06",
    title: "Process Automation",
    image: "/services/automation.jpg",
    category: "[ Workflow Optimization ]",
    slug: "automation",
  },
  {
    id: "4",
    number: "04 / 06",
    title: "Enterprise Solutions",
    image: "/services/enterprise.jpg",
    category: "[ Custom Systems ]",
    slug: "enterprise",
  },
  {
    id: "5",
    number: "05 / 06",
    title: "Cloud Infrastructure",
    image: "/services/cloud-infrastructure.jpg",
    category: "[ DevOps & Deployment ]",
    slug: "cloud-infrastructure",
  },
  {
    id: "6",
    number: "06 / 06",
    title: "API Development",
    image: "/services/api-development.jpg",
    category: "[ Backend Services ]",
    slug: "api-development",
  },
];
